### ISSUE TITLE
Review request for chapters 1 and 2 

### ISSUE THREAD

**Issue by kamuda1** [arfc/kamuda-2019-dissertation#1]
Attached is a PDF in case the latex doesn't build on a specific machine. The PDF was built using Overleaf.

[Kamuda_Dissertation_updated.pdf](https://github.com/arfc/kamuda-2019-dissertation/files/3162476/Kamuda_Dissertation_updated.pdf)

**Comment by katyhuff** [comment]
up to page 20. 
[Kamuda_Dissertation_updated.pdf](https://github.com/arfc/kamuda-2019-dissertation/files/3233971/Kamuda_Dissertation_updated.pdf)

**Comment by katyhuff** [comment]
[Kamuda_Dissertation_updated.pdf](https://github.com/arfc/kamuda-2019-dissertation/files/3297133/Kamuda_Dissertation_updated.pdf)

New issue open in base repo.
